version: '3.9'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.51.0
    container_name: jaeger
    restart: always
    # ports:
    #   - "16686:16686"

  otel-collector:
    image: otel/opentelemetry-collector:0.90.0
    restart: always
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-trace-collector-config.yaml:/etc/otel-collector-config.yaml
    hostname: otel-collector
    # ports:
    #   - "13133:13133" # 健康检查扩展
    #   - "4317:4317"   # OTLP gRPC 接收器
    depends_on:
      - jaeger

  emqx1:
    image: emqx/emqx-enterprise:5.8.0
    container_name: emqx1
    restart: always
    hostname: emqx1-cluster.emqx.io
    environment:
      - EMQX_NODE__NAME=emqx1@emqx1-cluster.emqx.io
      - EMQX_CLUSTER__DISCOVERY_STRATEGY=static
      - EMQX_LOG__CONSOLE__LEVEL=debug
      - EMQX_DASHBOARD__DEFAULT_PASSWORD=public123
      - EMQX_OPENTELEMETRY__EXPORTER__ENDPOINT="http://otel-collector:4317"
      - EMQX_OPENTELEMETRY__TRACES__ENABLE=true
      - EMQX_OPENTELEMETRY__TRACES__FILTER__TRACE_ALL=true
      - EMQX_CLUSTER__STATIC__SEEDS=emqx1@emqx1-cluster.emqx.io,emqx2@emqx2-cluster.emqx.io,emqx3@emqx3-cluster.emqx.io

  emqx2:
    image: emqx/emqx-enterprise:5.8.0
    container_name: emqx2
    restart: always
    hostname: emqx2-cluster.emqx.io
    environment:
      - EMQX_NODE__NAME=emqx2@emqx2-cluster.emqx.io
      - EMQX_CLUSTER__DISCOVERY_STRATEGY=static
      - EMQX_LOG__CONSOLE__LEVEL=debug
      - EMQX_DASHBOARD__DEFAULT_PASSWORD=public123
      - EMQX_OPENTELEMETRY__EXPORTER__ENDPOINT="http://otel-collector:4317"
      - EMQX_OPENTELEMETRY__TRACES__ENABLE=true
      - EMQX_OPENTELEMETRY__TRACES__FILTER__TRACE_ALL=true
      - EMQX_CLUSTER__STATIC__SEEDS=emqx1@emqx1-cluster.emqx.io,emqx2@emqx2-cluster.emqx.io,emqx3@emqx3-cluster.emqx.io

  emqx3:
    image: emqx/emqx-enterprise:5.8.0
    container_name: emqx3
    restart: always
    hostname: emqx3-cluster.emqx.io
    environment:
      - EMQX_NODE__NAME=emqx3@emqx3-cluster.emqx.io
      - EMQX_CLUSTER__DISCOVERY_STRATEGY=static
      - EMQX_LOG__CONSOLE__LEVEL=debug
      - EMQX_DASHBOARD__DEFAULT_PASSWORD=public123
      - EMQX_OPENTELEMETRY__EXPORTER__ENDPOINT="http://otel-collector:4317"
      - EMQX_OPENTELEMETRY__TRACES__ENABLE=true
      - EMQX_OPENTELEMETRY__TRACES__FILTER__TRACE_ALL=true
      - EMQX_CLUSTER__STATIC__SEEDS=emqx1@emqx1-cluster.emqx.io,emqx2@emqx2-cluster.emqx.io,emqx3@emqx3-cluster.emqx.io

  # emqx-rep1:
  #   image: emqx/emqx-enterprise:5.8.0-alpha.1-gbc25fd3c
  #   container_name: emqx-rep1
  #   hostname: emqx-rep1-cluster.emqx.io
  #   environment:
  #     - EMQX_NODE__NAME=emqx-rep1@emqx-rep1-cluster.emqx.io
  #     - EMQX_NODE__ROLE=replicant
  #     - EMQX_CLUSTER__DISCOVERY_STRATEGY=static
  #     - EMQX_LOG__CONSOLE__LEVEL=debug
  #     - EMQX_DASHBOARD__DEFAULT_PASSWORD=public123
  #     - EMQX_CLUSTER__STATIC__SEEDS=emqx1@emqx1-cluster.emqx.io,emqx2@emqx2-cluster.emqx.io,emqx3@emqx3-cluster.emqx.io,emqx-rep1@emqx-rep1-cluster.emqx.io,emqx-rep2@emqx-rep2-cluster.emqx.io,emqx-rep3@emqx-rep3-cluster.emqx.io

  # emqx-rep2:
  #   image: emqx/emqx-enterprise:5.8.0-alpha.1-gbc25fd3c
  #   container_name: emqx-rep2
  #   hostname: emqx-rep2-cluster.emqx.io
  #   environment:
  #     - EMQX_NODE__NAME=emqx-rep2@emqx-rep2-cluster.emqx.io
  #     - EMQX_NODE__ROLE=replicant
  #     - EMQX_CLUSTER__DISCOVERY_STRATEGY=static
  #     - EMQX_LOG__CONSOLE__LEVEL=debug
  #     - EMQX_DASHBOARD__DEFAULT_PASSWORD=public123
  #     - EMQX_CLUSTER__STATIC__SEEDS=emqx1@emqx1-cluster.emqx.io,emqx2@emqx2-cluster.emqx.io,emqx3@emqx3-cluster.emqx.io,emqx-rep1@emqx-rep1-cluster.emqx.io,emqx-rep2@emqx-rep2-cluster.emqx.io,emqx-rep3@emqx-rep3-cluster.emqx.io

  # emqx-rep3:
  #   image: emqx/emqx-enterprise:5.8.0-alpha.1-gbc25fd3c
  #   container_name: emqx-rep3
  #   hostname: emqx-rep3-cluster.emqx.io
  #   environment:
  #     - EMQX_NODE__NAME=emqx-rep3@emqx-rep3-cluster.emqx.io
  #     - EMQX_NODE__ROLE=replicant
  #     - EMQX_CLUSTER__DISCOVERY_STRATEGY=static
  #     - EMQX_LOG__CONSOLE__LEVEL=debug
  #     - EMQX_DASHBOARD__DEFAULT_PASSWORD=public123
  #     - EMQX_CLUSTER__STATIC__SEEDS=emqx1@emqx1-cluster.emqx.io,emqx2@emqx2-cluster.emqx.io,emqx3@emqx3-cluster.emqx.io,emqx-rep1@emqx-rep1-cluster.emqx.io,emqx-rep2@emqx-rep2-cluster.emqx.io,emqx-rep3@emqx-rep3-cluster.emqx.io

  # nginx:
  #   image: nginx
  #   container_name: nginx
  #   volumes:
  #     - $PWD/nginx.conf:/etc/nginx/nginx.conf
  #     - $PWD/certs:/etc/nginx/certs

networks:
  emqx-net:
    driver: emqx-net
