receivers:
  otlp:
    protocols:
      grpc:

exporters:
  # use infulxdb exporter to write in datalayers
  influxdb/v1:
    endpoint: http://influxdbv1:8086
    v1_compatibility:
      enabled: true
      db: mydb
      username: admin
      password: public123

processors:
  batch:

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [influxdb/v1]
