receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  # use infulxdb exporter to write in datalayers
  influxdb/v1:
    endpoint: http://nginx:8086
    v1_compatibility:
      enabled: true
      db: mydb
      username: admin
      password: public123

  influxdb/datalayers:
    endpoint: http://nginx:8086
    v1_compatibility:
      enabled: true
      db: mydb
      username: admin
      password: public123

processors:
  batch:

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters:
        - influxdb/v1
        - influxdb/datalayers
