receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  influxdb/v1:
    endpoint: http://nginx:8086
    span_dimensions:
      ## Span Name always as the first tag
      - span.name
      - service.name
      # Client CONNECT span
      - client.connect.clientid
      - client.connect.username
      - client.connect.peername
      # Client DISCONNECT span
      - client.disconnect.clientid
      - client.disconnect.username
      # Client SUBSCRIBE span
      - client.subscribe.topic_filters
      # Client UNSUBSCRIBE span
      - client.unsubscribe.topic_filters
      - message.msg_id
    v1_compatibility:
      enabled: true
      db: mydb
      username: admin
      password: public123

  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

processors:
  batch:

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters:
        - influxdb/v1
        - otlp
